#define TYSTUDIO_VERSION "0.5.0 Beta 2"

#include "tycommon.h"


char  tyabout[]="is a part of TyStudio "TYSTUDIO_VERSION""NEWLINE""NEWLINE""
		"Copyright (c) 2002, 2003, 2015 The TyStudio Project Team"NEWLINE""NEWLINE""
		"TyStudio project suite is composed of:"NEWLINE""
		"Programs:"NEWLINE""
		"TyEditor, tytranscode, tydemux, typrocess, tyls, tyget and tychopper"NEWLINE""
		"Libraries:"NEWLINE""
		"tythreadlib, typrocesslib, tydemuxlib, tytranscodelib, tymplexlib"NEWLINE""
		"Tivo servers:"NEWLINE""
		"tyindex, tyserver"NEWLINE""
		"TyStudio make usage of:"NEWLINE""
		"QT, mpeg2dec, mplex, ffmpeg, mfslib, playitsam"NEWLINE""NEWLINE""
		"All components written by the TyStudio Project Team are released under"NEWLINE""
		"the terms of the GNU General Public License as published by"NEWLINE""
		"the Free Software Foundation; either version 2 of the License, or"NEWLINE""
		"(at your option) any later version."NEWLINE""NEWLINE""
		"The TyStudio Project Team is composed of:"NEWLINE""
		"John Barrett (MrBassMan)"NEWLINE""
		"Olaf Beck"NEWLINE""
		"Rowan McFarland"NEWLINE""NEWLINE""
		"Contributors to TyStudio:"NEWLINE""
		"Guy Brooker"NEWLINE""
		"Christopher Wingert"NEWLINE""
		"Justin Decker"NEWLINE""
		"Riley "NEWLINE""
		"Kurt J. Lind"NEWLINE""
		"Allan Stirling"NEWLINE""
		"Alun Jenkins"NEWLINE""
		"Plus, all of those who have submitted TyStreams for analysis"NEWLINE""NEWLINE""
		"For support visit the TyStudio web site at "NEWLINE""
		"http://dvd-create.sourceforge.net/tystudio"NEWLINE""
		"or http://sourceforge.net/projects/dvd-create/ or subscribe to"NEWLINE""
		"the TyStudio mailing list at <dvd-create-tystudio@lists.sourceforge.net>"NEWLINE""
		"Alternatively, visit the TyStudio thread at the appropriate forum at"NEWLINE""
		"the dealdatabase at "NEWLINE""
		"http://www.dealdatabase.com/forum/forumdisplay.php?s=&forumid=39"NEWLINE"";
